In [19]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [9]:
df = pd.read_csv(r".\src\boston.csv")

df.head(10)

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.21124,12.5,7.87,0.0,0.524,5.631,100.0,6.0821,5,311.0,15.2,386.63,29.93,16.5
1,0.21124,12.5,7.87,0.0,0.524,5.631,100.0,6.0821,5,311.0,15.2,386.63,29.93,16.5
2,0.21124,12.5,7.87,0.0,0.524,5.631,100.0,6.0821,5,311.0,15.2,386.63,29.93,16.5
3,0.03237,NaN,2.18,0.0,0.458,6.998,NaN,6.0622,3,NaN,18.7,NaN,2.94,NaN
4,NaN,0.0,2.18,NaN,NaN,NaN,54.2,6.0622,3,222.0,18.7,396.90,5.33,36.2
5,0.02985,0.0,2.18,0.0,0.458,6.430,58.7,6.0622,3,NaN,NaN,394.12,5.21,28.7
6,0.08829,12.5,7.87,0.0,0.524,6.012,66.6,5.5605,5,311.0,15.2,395.60,12.43,22.9
7,0.14455,12.5,7.87,0.0,0.524,6.172,96.1,5.9505,5,311.0,15.2,396.90,NaN,27.1
8,0.21124,12.5,7.87,0.0,0.524,5.631,100.0,6.0821,5,311.0,15.2,386.63,29.93,16.5
9,0.17004,12.5,7.87,0.0,0.524,6.004,85.9,6.5921,5,311.0,15.2,386.71,17.10,18.9

In [10]:
df.tail()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
501,0.06263,0.0,11.93,0.0,0.573,6.593,69.1,2.4786,1,273.0,21.0,391.99,9.67,22.4
502,0.04527,0.0,11.93,0.0,0.573,6.120,76.7,2.2875,1,273.0,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0.0,0.573,6.976,91.0,2.1675,1,273.0,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0.0,0.573,6.794,89.3,2.3889,1,273.0,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0.0,0.573,6.030,80.8,2.5050,1,273.0,21.0,396.90,7.88,11.9

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 14 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   CRIM     505 non-null    float64
 1   ZN       505 non-null    float64
 2   INDUS    506 non-null    float64
 3   CHAS     505 non-null    float64
 4   NOX      505 non-null    float64
 5   RM       505 non-null    float64
 6   AGE      505 non-null    float64
 7   DIS      506 non-null    float64
 8   RAD      506 non-null    int64
 9   TAX      504 non-null    float64
 10  PTRATIO  505 non-null    float64
 11  B        505 non-null    float64
 12  LSTAT    505 non-null    float64
 13  MEDV     505 non-null    float64
dtypes: float64(13), int64(1)
memory usage: 55.5 KB

### I. Prepare the data with missing values.

In [2]:
def make_missing_values(
    src_path: str,
    tgt_path: str,
    n_rows: int = 100,
    missing_per_col: float = 0.1,
) -> None:
    """
    This function loads your DataFrame and stores it as a separate .csv file for your experiments with missing data.
    
    :param src_path: Path to the original source .csv file to read.
    :param tgt_path: Path where the modified .csv file with missing values will be saved.
    :param n_rows: Number of rows to read from the source file.
    :param missing_per_col: The fraction of values to drop per column (e.g., 0.2 for 20% missing data). Must be between 0.0 and 1.0.
    :return: None
    """
    
    # 1. Load the specific number of rows from the source CSV
    df = pd.read_csv(src_path, nrows=n_rows)
    
    # 2. Calculate the exact number of missing values to inject per column
    # We use len(df) in case the source file has fewer rows than n_rows
    n_missing = int(len(df) * missing_per_col)
    
    # 3. Iterate through each column and inject NaNs randomly
    for col in df.columns:
        # Select random indices without replacement, so we don't pick the same row twice
        missing_indices = np.random.choice(df.index, size=n_missing, replace=False)
        
        # Assign NaN to the selected random indices for the current column
        df.loc[missing_indices, col] = np.nan
        
    # 4. Save the modified DataFrame to the target path
    df.to_csv(tgt_path, index=False)

In [14]:
make_missing_values(
    src_path=r".\src\boston.csv",
    tgt_path=r".\miss_boston.csv",
)

In [15]:
df_miss = pd.read_csv(r".\src\miss_boston.csv")
df_miss.head()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.21124,12.5,7.87,0.0,0.524,5.631,100.0,NaN,NaN,311.0,15.2,386.63,29.93,16.5
1,0.21124,12.5,7.87,0.0,0.524,5.631,100.0,6.0821,NaN,311.0,NaN,386.63,29.93,16.5
2,0.21124,12.5,7.87,0.0,0.524,5.631,100.0,6.0821,5.0,311.0,15.2,NaN,29.93,16.5
3,0.03237,NaN,2.18,0.0,NaN,6.998,NaN,6.0622,3.0,NaN,18.7,NaN,2.94,NaN
4,NaN,0.0,2.18,NaN,NaN,NaN,54.2,6.0622,NaN,222.0,18.7,396.90,5.33,36.2

In [16]:
df_miss.tail()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
95,NaN,0.0,2.89,0.0,0.445,6.625,57.8,NaN,2.0,276.0,18.0,357.98,6.65,28.4
96,0.11504,0.0,NaN,0.0,0.445,6.163,69.6,3.4952,2.0,276.0,18.0,391.83,NaN,21.4
97,0.12083,0.0,2.89,0.0,0.445,8.069,76.0,3.4952,2.0,276.0,18.0,396.90,4.21,38.7
98,0.08187,0.0,NaN,0.0,0.445,7.820,36.9,3.4952,2.0,276.0,18.0,393.53,3.57,43.8
99,0.06860,0.0,2.89,0.0,0.445,7.416,62.5,3.4952,2.0,276.0,NaN,396.90,NaN,33.2

In [17]:
df_miss.isnull().sum()

CRIM       11
ZN         11
INDUS      10
CHAS       11
NOX        10
RM         10
AGE        11
DIS        10
RAD        10
TAX        11
PTRATIO    11
B          11
LSTAT      11
MEDV       11
dtype: int64

In [18]:
df_miss.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 14 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   CRIM     89 non-null     float64
 1   ZN       89 non-null     float64
 2   INDUS    90 non-null     float64
 3   CHAS     89 non-null     float64
 4   NOX      90 non-null     float64
 5   RM       90 non-null     float64
 6   AGE      89 non-null     float64
 7   DIS      90 non-null     float64
 8   RAD      90 non-null     float64
 9   TAX      89 non-null     float64
 10  PTRATIO  89 non-null     float64
 11  B        89 non-null     float64
 12  LSTAT    89 non-null     float64
 13  MEDV     89 non-null     float64
dtypes: float64(14)
memory usage: 11.1 KB

### II. Working with missing values

In [33]:
#1. Remove rows with any missing values (Do NOT same results in the working DataFrame).
df_remove_rows = df_miss.dropna(axis=0, how='any')
df_remove_rows.head(10)

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
8,0.21124,12.5,7.87,0.0,0.524,5.631,100.0,6.0821,5.0,311.0,15.2,386.63,29.93,16.5
13,0.62976,0.0,8.14,0.0,0.538,5.949,61.8,4.7075,4.0,307.0,21.0,396.90,8.26,20.4
17,0.21124,12.5,7.87,0.0,0.524,5.631,100.0,6.0821,5.0,311.0,15.2,386.63,29.93,16.5
30,1.13081,0.0,8.14,0.0,0.538,5.713,94.1,4.2330,4.0,307.0,21.0,360.17,22.60,12.7
33,1.15172,0.0,8.14,0.0,0.538,5.701,95.0,3.7872,4.0,307.0,21.0,358.77,18.35,13.1
40,0.03359,75.0,2.95,0.0,0.428,7.024,15.8,5.4011,3.0,252.0,18.3,395.62,1.98,34.9
41,0.12744,0.0,6.91,0.0,0.448,6.770,2.9,5.7209,3.0,233.0,17.9,385.41,4.84,26.6
42,0.14150,0.0,6.91,0.0,0.448,6.169,6.6,5.7209,3.0,233.0,17.9,383.37,5.81,25.3
44,0.12269,0.0,6.91,0.0,0.448,6.069,40.0,5.7209,3.0,233.0,17.9,389.39,9.55,21.2
46,0.18836,0.0,6.91,0.0,0.448,5.786,33.3,5.1004,3.0,233.0,17.9,396.90,14.15,20.0

In [37]:
df_remove_rows.isnull().sum()

CRIM       0
ZN         0
INDUS      0
CHAS       0
NOX        0
RM         0
AGE        0
DIS        0
RAD        0
TAX        0
PTRATIO    0
B          0
LSTAT      0
MEDV       0
dtype: int64

#### This method is best used when the dataset is very large, and the rows with missing data represent only a tiny fraction of the total data. But it is dangerous if it causes a massive loss of usable data.

In [43]:
#2. Remove cols with any missing values (Do NOT same results in the working DataFrame).
df_remove_cols = df_miss.dropna(axis=1, how='any')
df_remove_cols.head(10)

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

#### This is a drastic measure, okay to use only when a specific column is missing a massive percentage of its data. Otherwise, you risk throwing away highly valuable features

In [46]:
#3. Remove rows with the specific number (or percent) of missing values (Do NOT same results in the working DataFrame).
df_remove_rows_by_number = df_miss.dropna(axis=0, thresh=10)
df_remove_rows_by_number.head(10)

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.21124,12.5,7.87,0.0,0.524,5.631,100.0,NaN,NaN,311.0,15.2,386.63,29.93,16.5
1,0.21124,12.5,7.87,0.0,0.524,5.631,100.0,6.0821,NaN,311.0,NaN,386.63,29.93,16.5
2,0.21124,12.5,7.87,0.0,0.524,5.631,100.0,6.0821,5.0,311.0,15.2,NaN,29.93,16.5
6,0.08829,12.5,NaN,0.0,0.524,6.012,NaN,5.5605,5.0,311.0,15.2,395.60,12.43,22.9
7,0.14455,12.5,7.87,0.0,0.524,6.172,96.1,5.9505,5.0,311.0,15.2,396.90,NaN,27.1
8,0.21124,12.5,7.87,0.0,0.524,5.631,100.0,6.0821,5.0,311.0,15.2,386.63,29.93,16.5
9,0.17004,12.5,7.87,0.0,0.524,NaN,85.9,6.5921,5.0,311.0,NaN,NaN,17.10,18.9
10,0.22489,12.5,7.87,0.0,0.524,6.377,94.3,6.3467,5.0,311.0,15.2,NaN,20.45,15.0
11,0.11747,12.5,7.87,0.0,0.524,6.009,82.9,6.2267,5.0,311.0,15.2,NaN,13.27,18.9
12,0.09378,12.5,7.87,0.0,0.524,5.889,NaN,5.4509,5.0,311.0,NaN,390.50,15.71,21.7

In [48]:
df_remove_rows_by_number.isnull().sum()

CRIM        9
ZN         10
INDUS       9
CHAS       10
NOX         7
RM          7
AGE         9
DIS         9
RAD         9
TAX         9
PTRATIO     9
B          10
LSTAT      11
MEDV       10
dtype: int64

#### This is a much smarter alternative to dropping rows blindly. It allows us to preserve rows that have mostly good, usable data, while safely discarding rows that are practically blank.

In [52]:
#4. Execute back filling of missing values (Do NOT same results in the working DataFrame).
df_bf = df_miss.bfill()
df_bf.head(10)

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.21124,12.5,7.87,0.0,0.524,5.631,100.0,6.0821,5.0,311.0,15.2,386.63,29.93,16.5
1,0.21124,12.5,7.87,0.0,0.524,5.631,100.0,6.0821,5.0,311.0,15.2,386.63,29.93,16.5
2,0.21124,12.5,7.87,0.0,0.524,5.631,100.0,6.0821,5.0,311.0,15.2,396.90,29.93,16.5
3,0.03237,0.0,2.18,0.0,0.524,6.998,54.2,6.0622,3.0,222.0,18.7,396.90,2.94,36.2
4,0.08829,0.0,2.18,0.0,0.524,6.012,54.2,6.0622,3.0,222.0,18.7,396.90,5.33,36.2
5,0.08829,0.0,2.18,0.0,0.524,6.012,58.7,6.0622,3.0,311.0,15.2,394.12,5.21,28.7
6,0.08829,12.5,7.87,0.0,0.524,6.012,96.1,5.5605,5.0,311.0,15.2,395.60,12.43,22.9
7,0.14455,12.5,7.87,0.0,0.524,6.172,96.1,5.9505,5.0,311.0,15.2,396.90,29.93,27.1
8,0.21124,12.5,7.87,0.0,0.524,5.631,100.0,6.0821,5.0,311.0,15.2,386.63,29.93,16.5
9,0.17004,12.5,7.87,0.0,0.524,6.377,85.9,6.5921,5.0,311.0,15.2,390.50,17.10,18.9

In [54]:
df_bf.isnull().sum()

CRIM       0
ZN         0
INDUS      0
CHAS       0
NOX        0
RM         0
AGE        0
DIS        0
RAD        0
TAX        0
PTRATIO    1
B          0
LSTAT      1
MEDV       0
dtype: int64

In [69]:
#5. Execute front filling of missing values (Do NOT same results in the working DataFrame).
df_ff = df_miss.ffill()
df_ff.head(10)

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.21124,12.5,7.87,0.0,0.524,5.631,100.0,NaN,NaN,311.0,15.2,386.63,29.93,16.5
1,0.21124,12.5,7.87,0.0,0.524,5.631,100.0,6.0821,NaN,311.0,15.2,386.63,29.93,16.5
2,0.21124,12.5,7.87,0.0,0.524,5.631,100.0,6.0821,5.0,311.0,15.2,386.63,29.93,16.5
3,0.03237,12.5,2.18,0.0,0.524,6.998,100.0,6.0622,3.0,311.0,18.7,386.63,2.94,16.5
4,0.03237,0.0,2.18,0.0,0.524,6.998,54.2,6.0622,3.0,222.0,18.7,396.90,5.33,36.2
5,0.03237,0.0,2.18,0.0,0.524,6.998,58.7,6.0622,3.0,222.0,18.7,394.12,5.21,28.7
6,0.08829,12.5,2.18,0.0,0.524,6.012,58.7,5.5605,5.0,311.0,15.2,395.60,12.43,22.9
7,0.14455,12.5,7.87,0.0,0.524,6.172,96.1,5.9505,5.0,311.0,15.2,396.90,12.43,27.1
8,0.21124,12.5,7.87,0.0,0.524,5.631,100.0,6.0821,5.0,311.0,15.2,386.63,29.93,16.5
9,0.17004,12.5,7.87,0.0,0.524,5.631,85.9,6.5921,5.0,311.0,15.2,386.63,17.10,18.9

In [70]:
df_ff.isnull().sum()

CRIM       0
ZN         0
INDUS      0
CHAS       0
NOX        0
RM         0
AGE        0
DIS        1
RAD        2
TAX        0
PTRATIO    0
B          0
LSTAT      0
MEDV       0
dtype: int64

In [58]:
#6. Execute filling by a specific values (median, mean, just value indicator like -1 for numerical or "missing" for object).

df_mean_fill = df_miss.fillna(df_miss.mean())
df_mean_fill.head(10)

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.211240,12.500000,7.87,0.0,0.524000,5.631000,100.000000,5.279612,4.066667,311.000000,15.200000,386.630000,29.93000,16.500000
1,0.211240,12.500000,7.87,0.0,0.524000,5.631000,100.000000,6.082100,4.066667,311.000000,18.564045,386.630000,29.93000,16.500000
2,0.211240,12.500000,7.87,0.0,0.524000,5.631000,100.000000,6.082100,5.000000,311.000000,15.200000,387.052697,29.93000,16.500000
3,0.032370,12.421348,2.18,0.0,0.472368,6.998000,56.635955,6.062200,3.000000,292.707865,18.700000,387.052697,2.94000,22.164045
4,0.270361,0.000000,2.18,0.0,0.472368,6.188522,54.200000,6.062200,4.066667,222.000000,18.700000,396.900000,5.33000,36.200000
5,0.270361,0.000000,2.18,0.0,0.472368,6.188522,58.700000,6.062200,3.000000,292.707865,18.564045,394.120000,5.21000,28.700000
6,0.088290,12.500000,6.93,0.0,0.524000,6.012000,56.635955,5.560500,5.000000,311.000000,15.200000,395.600000,12.43000,22.900000
7,0.144550,12.500000,7.87,0.0,0.524000,6.172000,96.100000,5.950500,5.000000,311.000000,15.200000,396.900000,11.94236,27.100000
8,0.211240,12.500000,7.87,0.0,0.524000,5.631000,100.000000,6.082100,5.000000,311.000000,15.200000,386.630000,29.93000,16.500000
9,0.170040,12.500000,7.87,0.0,0.524000,6.188522,85.900000,6.592100,5.000000,311.000000,18.564045,387.052697,17.10000,18.900000

In [68]:
df_miss["TAX"].describe()

count     89.000000
mean     292.707865
std       44.310937
min      216.000000
25%      270.000000
50%      305.000000
75%      311.000000
max      469.000000
Name: TAX, dtype: float64

In [67]:
df_mean_fill["TAX"].describe()

count    100.000000
mean     292.707865
std       41.776752
min      216.000000
25%      270.000000
50%      292.707865
75%      307.000000
max      469.000000
Name: TAX, dtype: float64

#### The overall mean of the column naturally remained exactly the same. However, the standard deviation decreased. This happens because we added multiple new data points exactly at the center of the distribution, which reduces the variance of the data points from the center

#### Best used for continuous, normally distributed numerical data that does not have extreme outliers

In [72]:
df_median_fill = df_miss.fillna(df_miss.median())
df_median_fill.head(10)

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.21124,12.5,7.87,0.0,0.524,5.631,100.0,5.2873,4.0,311.0,15.2,386.63,29.93,16.5
1,0.21124,12.5,7.87,0.0,0.524,5.631,100.0,6.0821,4.0,311.0,18.7,386.63,29.93,16.5
2,0.21124,12.5,7.87,0.0,0.524,5.631,100.0,6.0821,5.0,311.0,15.2,394.12,29.93,16.5
3,0.03237,0.0,2.18,0.0,0.451,6.998,56.8,6.0622,3.0,305.0,18.7,394.12,2.94,21.4
4,0.12083,0.0,2.18,0.0,0.451,6.096,54.2,6.0622,4.0,222.0,18.7,396.90,5.33,36.2
5,0.12083,0.0,2.18,0.0,0.451,6.096,58.7,6.0622,3.0,305.0,18.7,394.12,5.21,28.7
6,0.08829,12.5,6.91,0.0,0.524,6.012,56.8,5.5605,5.0,311.0,15.2,395.60,12.43,22.9
7,0.14455,12.5,7.87,0.0,0.524,6.172,96.1,5.9505,5.0,311.0,15.2,396.90,9.55,27.1
8,0.21124,12.5,7.87,0.0,0.524,5.631,100.0,6.0821,5.0,311.0,15.2,386.63,29.93,16.5
9,0.17004,12.5,7.87,0.0,0.524,6.096,85.9,6.5921,5.0,311.0,18.7,394.12,17.10,18.9

In [74]:
df_miss["TAX"].describe()

count     89.000000
mean     292.707865
std       44.310937
min      216.000000
25%      270.000000
50%      305.000000
75%      311.000000
max      469.000000
Name: TAX, dtype: float64

In [73]:
df_median_fill["TAX"].describe()

count    100.0000
mean     294.0600
std       41.9552
min      216.0000
25%      270.0000
50%      305.0000
75%      307.0000
max      469.0000
Name: TAX, dtype: float64

#### The mean shifted slightly closer to the median, and the standard deviation also decreased, though often less uniformly than mean-filling. This method safely preserved the general shape of our skewed data without letting outliers dictate the missing values.

In [61]:
df_indicator_fill = df_miss.fillna(-1)
df_indicator_fill.head(10)

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.21124,12.5,7.87,0.0,0.524,5.631,100.0,-1.0000,-1.0,311.0,15.2,386.63,29.93,16.5
1,0.21124,12.5,7.87,0.0,0.524,5.631,100.0,6.0821,-1.0,311.0,-1.0,386.63,29.93,16.5
2,0.21124,12.5,7.87,0.0,0.524,5.631,100.0,6.0821,5.0,311.0,15.2,-1.00,29.93,16.5
3,0.03237,-1.0,2.18,0.0,-1.000,6.998,-1.0,6.0622,3.0,-1.0,18.7,-1.00,2.94,-1.0
4,-1.00000,0.0,2.18,-1.0,-1.000,-1.000,54.2,6.0622,-1.0,222.0,18.7,396.90,5.33,36.2
5,-1.00000,0.0,2.18,0.0,-1.000,-1.000,58.7,6.0622,3.0,-1.0,-1.0,394.12,5.21,28.7
6,0.08829,12.5,-1.00,0.0,0.524,6.012,-1.0,5.5605,5.0,311.0,15.2,395.60,12.43,22.9
7,0.14455,12.5,7.87,0.0,0.524,6.172,96.1,5.9505,5.0,311.0,15.2,396.90,-1.00,27.1
8,0.21124,12.5,7.87,0.0,0.524,5.631,100.0,6.0821,5.0,311.0,15.2,386.63,29.93,16.5
9,0.17004,12.5,7.87,0.0,0.524,-1.000,85.9,6.5921,5.0,311.0,-1.0,-1.00,17.10,18.9

#### This is excellent when the absence of data is actually a signal itself like for creating a cluster. But for my dataset can act weird on statistics

### Final cleaning

In [91]:
df_clean = df_miss.dropna(axis=0, thresh=11)
df_clean["CHAS"] = df_clean["CHAS"].fillna(0)
df_clean = df_clean.fillna(df_clean.median())

df_clean.head(10)

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.21124,12.5,7.87,0.0,0.524,5.631,100.0,5.2873,4.0,311.0,15.2,386.63,29.93,16.5
1,0.21124,12.5,7.87,0.0,0.524,5.631,100.0,6.0821,4.0,311.0,18.5,386.63,29.93,16.5
2,0.21124,12.5,7.87,0.0,0.524,5.631,100.0,6.0821,5.0,311.0,15.2,393.54,29.93,16.5
6,0.08829,12.5,6.91,0.0,0.524,6.012,56.8,5.5605,5.0,311.0,15.2,395.60,12.43,22.9
7,0.14455,12.5,7.87,0.0,0.524,6.172,96.1,5.9505,5.0,311.0,15.2,396.90,9.68,27.1
8,0.21124,12.5,7.87,0.0,0.524,5.631,100.0,6.0821,5.0,311.0,15.2,386.63,29.93,16.5
9,0.17004,12.5,7.87,0.0,0.524,6.096,85.9,6.5921,5.0,311.0,18.5,393.54,17.10,18.9
10,0.22489,12.5,7.87,0.0,0.524,6.377,94.3,6.3467,5.0,311.0,15.2,393.54,20.45,15.0
11,0.11747,12.5,7.87,0.0,0.524,6.009,82.9,6.2267,5.0,311.0,15.2,393.54,13.27,18.9
12,0.09378,12.5,7.87,0.0,0.524,5.889,56.8,5.4509,5.0,311.0,18.5,390.50,15.71,21.7

In [94]:
#final proof
df_clean.isnull().sum().sum() == 0

np.True_

#### The dataset has been successfully prepared, with missing values handled based on their data types and distributions